[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
  nnoremap [gitgutter] <Nop>
  nmap <C-h> [gitgutter]
  nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR>
  nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
'''

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = '''
#   nnoremap [denite] <Nop>
#   nmap <C-n> [denite]
#   nnoremap <silent> [denite]g :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
#   nnoremap <silent> [denite]r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
#   nnoremap <silent> [denite]p :<C-u>Denite file_rec<CR>
#   call denite#custom#option('default', 'prompt', '>')
#   call denite#custom#option('_', 'highlight_matched_range', 'None')
#   call denite#custom#option('_', 'highlight_matched_char', 'None')
#   call denite#custom#map('insert', "<Tab>", '<denite:move_to_next_line>')
#   call denite#custom#map('insert', "<S-Tab>", '<denite:move_to_previous_line>')
#   call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
#   call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
#   call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
#   call denite#custom#var('grep', 'command', ['pt', '--follow', '--nogroup', '--nocolor', '--hidden'])
#   call denite#custom#var('grep', 'default_opts', [])
#   call denite#custom#var('grep', 'recursive_opts', [])
#   call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
# '''

# [[plugins]]
# repo = 'hrsh7th/vim-vsnip'
# depends = ['vim-vsnip-integ', 'friendly-snippets']
# on_event = 'InsertEnter'
# hook_add = '''
# " Expand
# imap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
# smap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
# " Jump forward or backward
# imap <expr> <C-k> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-k>'
# smap <expr> <C-k> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-k>'
# " imap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
# " smap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
# '''
#
# [[plugins]]
# repo = 'matsui54/vim-vsnip-integ'
#
# [[plugins]]
# repo = 'rafamadriz/friendly-snippets'
