.Dd June 24, 2013
.Dt Z \&1 "User Commands Manual"
.Os Unix
.Sh NAME
.Nm z
.Nd jump around
.Sh SYNOPSIS
.Nm z
.Op Fl hclrtx
.Op Ar string ...
.Sh AVAILABILITY
bash, zsh
.Sh DESCRIPTION
Tracks your most used directories, based on
.Sq frecency .
.P
After a short learning phase,
.Nm
will take you to the most
.Sq frecent
directory that matches all of the patterns given on the command line.
.Pp
Each pattern is a substring that the directory to look for must
contain, not a regular expression like in the original version nor a
glob pattern that you can use in shell completion described below.
.Pp
For convenience, a trailing slash in a pattern is treated specially so
that the pattern also matches directories ending with the pattern
string minus the trailing slash.  That is, for instance, a pattern
.Sq Ic log/
matches
.Pa /var/log
as well as
.Pa /service/nginx/log/main ,
but not
.Pa /home/user/logs .
.Pp
In addition to this, a double slash at the beginning or at the end of
a pattern has special meanings.  A double slash at the beginning
denotes the root directory, and a double slash at the end denotes the
end of a path.  That is, a pattern
.Sq Ic //var
matches
.Pa /var/log
but does not match
.Pa /home/user/var/log ,
and a pattern
.Sq Ic src//
matches
.Pa /home/user/src/screen/src
but does not match
.Pa /home/user/src/screen .
.Pp
The
.Pa $HOME
part in a directory name is excluded before matching so that a word or
substring that is in your account name does not hit every single
directory under your home directory.
.Sh OPTIONS
.Bl -tag -compact -width "-l"
.It Fl h
Show a brief help message.
.Pp
.It Fl c
Restrict matches to subdirectories of the current directory.
.Pp
.It Fl l
List only.
.Pp
.It Fl r
Sort by rank instead of
.Sq frecency .
.Pp
.It Fl t
Sort by recency instead of
.Sq frecency .
.Pp
.It Fl x
Remove the current directory from the datafile.
.El
.Pp
Nonexistent directories are omitted from output and ignored in moving
and completion but kept in database for future use.
.Pp
In listing, only top 20 directories are shown if stdout is a terminal.
To show all, run
.Nm
with a pipe, like
.Sq Ic "z | cat"
or
.Sq Ic "z | less" .
.Sh EXAMPLES
.Bl -tag -compact -width "z foo bar"
.It Ic "z foo"
cd to most frecent directory matching foo
.It Ic "z foo bar"
cd to most frecent directory matching foo and bar
.It Ic "z -r foo"
cd to highest ranked directory matching foo
.It Ic "z -t foo"
cd to most recently accessed directory matching foo
.It Ic "z -l foo"
list all directories matching foo (by frecency)
.El
.Sh "NOTES"
.Ss "Installation:"
.Bl -enum -offset 3n
.It
Source
.Pa z.sh
from your
.Pa $HOME/.bashrc
or
.Pa $HOME/.zshrc
like this:
.Dl . /path/to/z.sh
.Pp
Note that if you are using
.Ic bash :
.Bl -dash -offset 1n
.It
The line should go something like this:
.Dl [[ -z $PS1 ]] || \&. /path/to/z.sh
because
.Xr bash 1
in some cases reads
.Pa $HOME/.bashrc
when the shell is not interactive and
.Pa z.sh
will emit an error message in that case.
.It
The line should better be put after defining a completion method for
.Ic cd
if any, because
.Pa z.sh
tries to enhance an existing completion definition.
.El
.It
cd around for a while to build up the db.
.It
PROFIT!!
.El
.Pp
.Ss "Optionally:"
.Bl -item -offset 3n
.It
Set
.Ev _Z_CMD
to change the command name (default
.Sq Ic z ) .
.It
Set
.Ev _Z_DATA
to change the data file name (default
.Sq Pa $HOME/.z ) .
.It
Set
.Ev _Z_NO_COMPLETE_CD
to disable advanced completion for
.Ic cd .
.It
Set
.Ev _Z_NO_RESOLVE_SYMLINKS
to prevent symlink resolution.
.It
Set
.Ev _Z_NO_PROMPT_COMMAND
to handle
.Ev PROMPT_COMMAND
(bash) /
.Ic precmd
(zsh) yourself.
.It
Set
.Ev _Z_EXCLUDE_DIRS
to an array of directories to exclude.
.El
.Pp
These settings should go in
.Pa .bashrc /
.Pa .zshrc
before the line added above.
.Pp
Install the provided man page
.Pa z.1
to somewhere in the man path like
.Pa /usr/local/man/man1 .
.Ss "Aging:"
The rank of directories maintained by
.Nm
undergoes aging based on a simple formula.  The rank of each entry is
incremented every time it is accessed.  When the sum of ranks is
greater than 6000, all ranks are multiplied by 0.99.  Entries with a
rank lower than 1 are forgotten.
.Ss "Frecency:"
Frecency is a portmanteau of
.Sq recent
and
.Sq frequency .
It is a weighted rank that depends on how often and how recently
something occurred.  As far as I know, Mozilla came up with the term.
.Pp
To
.Nm ,
a directory that has low ranking but has been accessed recently will
quickly have higher rank than a directory accessed frequently a long
time ago.
.Pp
Frecency is determined at runtime.
.Ss "Common:"
When multiple directories match all queries, and they all have a
common prefix,
.Nm
will cd to the shortest matching directory, without regard to
priority.  This has been in effect, if undocumented, for quite some
time, but should probably be configurable or reconsidered.
.Ss "Shell Completion:"
.Nm
supports interactive shell completion.  After typing a string
fragment, press
.Ic TAB
to complete on directories that matches the pattern.  In addition to
the double slash notation described above, and glob matching works
here.
.Pp
.Nm
also enhances the completion for the
.Ic cd
command so you don't even need to learn about
.Nm
at all.  If you don't like this feature, it can be disabled.  See the
next section.
.Pp
.Sh ENVIRONMENT
A function
.Fn _z_cmd
is defined.
.Pp
The contents of the variable
.Ev _Z_CMD
is aliased to
.Sq Ic _z_cmd .
If not set,
.Ev _Z_CMD
defaults to
.Ic z .
.P
The environment variable
.Ev _Z_DATA
can be used to control the data file location.  If it is not defined,
the location defaults to
.Sq Pa $HOME/.z .
.Pp
The environment variable
.Ev _Z_NO_RESOLVE_SYMLINKS
can be set to prevent resolving of symlinks.  If it is not set,
symbolic links will be resolved when added to the data file.
.Pp
In bash,
.Nm
prepends a command to the
.Ev PROMPT_COMMAND
environment variable to maintain its database.  In zsh,
.Nm
appends a function
.Ic _z_precmd
to the
.Ic precmd_functions
array.
.Pp
The environment variable
.Ev _Z_NO_COMPLETE_CD
can be set to disable advanced completion for
.Ic cd .
.Pp
The environment variable
.Ev _Z_NO_PROMPT_COMMAND
can be set if you want to handle
.Ev PROMPT_COMMAND
or
.Ic precmd
yourself.
.Pp
The environment variable
.Ev _Z_EXCLUDE_DIRS
can be set to an array of directories to exclude from tracking.
.Ev HOME
is always excluded.  Each element must be an absolute path, and if it
ends with a slash, all its subdirectories are also excluded.
.Sh FILES
Data is stored in
.Pa $HOME/.z .  This can be overridden by setting the
.Ev _Z_DATA
environment variable.  When initialized,
.Nm
will raise an error if this path is a directory, and not function
correctly.
.Pp
A man page
.Pq Pa z.1
is provided.
.Sh SEE ALSO
.Xr autojump 1 ,
.Xr bash 1 ,
.Xr cdargs 1 ,
.Xr j 1 ,
.Xr zshall 1
.Sh AUTHORS
.An rupa deadwyler Aq rupa@lrrr.us
.An Akinori MUSHA Aq knu@iDaemons.org
.Sh HISTORY
.Nm
was originally deveoloped by rupa deadwyler as a successor to
.Xr j 1 ,
a python free alternative to Joel Schaerer's
.Xr autojump 1 .
The original version is maintained at
.Aq Pa https://github.com/rupa/z .
.Pp
This fork was started by Akinori MUSHA in early 2013 to improve
zsh/bash completion usability and search results.
.Pp
The pattern matching conventions described above are exclusive
features of this fork, while the data file format and the core
algorithm are kept compatible with those of the original version.
.Sh BUGS
Please file bugs at
.Aq Pa https://github.com/knu/z .
